about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path("", views.about , name="about"),
]

adiva/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('home.urls', namespace='home')),
    path("about/", include('about.urls', namespace='about')),
    path("career/", include('careers.urls', namespace='career')),
    path("csr/", include('csr.urls', namespace='csr')),
    path("service/", include('service.urls', namespace='service')),
    path("legal/", include('legal.urls', namespace='legal')),
    path("faqs/", include('faqs.urls', namespace='faqs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

careers/urls.py
from django.urls import path

from . import views

app_name = 'careers'

urlpatterns = [
    path("", views.career, name="career"),
]

csr/urls.py
from django.urls import path

from . import views

app_name = 'csr'

urlpatterns = [
    path("", views.csr, name="csr"),
]

faqs/urls.py
from django.urls import path

from . import views

app_name = 'faqs'

urlpatterns = [
    path("", views.faqs, name="faqs"),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path("", views.home , name="home"),
]

legal/urls.py
from django.urls import path

from . import views

app_name = 'legal'

urlpatterns = [
    path("", views.legal, name="legal"),
]

mindset/urls.py
from django.urls import path

from . import views

app_name = 'mindset'

urlpatterns = [
    path("", views.mindset, name="mindset"),
]

service/urls.py
from django.urls import path

from . import views

app_name = 'service'

urlpatterns = [
    path("", views.service, name="service"),
]

about/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models

# Create your models here.

csr/models.py
from django.db import models

# Create your models here.

faqs/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

legal/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render
from django.http import HttpResponse

def about(request):
      return render(request, 'pages/about.html', {})
    
    

careers/views.py
from django.shortcuts import render
from django.http import HttpResponse


def career(request):
      return render(request, 'pages/career.html', {})
    

core/views.py
from django.shortcuts import render

# Create your views here.

csr/views.py
from django.shortcuts import render

def csr(request):
      return render(request, 'pages/csr.html', {})
    

faqs/views.py
from django.shortcuts import render

def faqs(request):
      return render(request, 'pages/faqs.html', {})
    

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return render(request, 'pages/home.html', {})
    

legal/views.py
from django.shortcuts import render

def legal(request):
      return render(request, 'pages/legal.html', {})
    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://vjs.zencdn.net/7.8.4/video-js.css" rel="stylesheet" />

    <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
    <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
    <link
      href="https://unpkg.com/@videojs/themes@1/dist/city/index.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/csr.css' %}">
    <link rel="stylesheet" href="{% static 'css/legal.css' %}">
    <link rel="stylesheet" href="{% static 'css/faqs.css' %}">

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    {% include 'partials/_navbar.html' %}
    {% include 'partials/_icon.html' %}

    {% block content %} {% endblock %}

    {% include 'partials/_footer.html' %}
    
    <script src="https://vjs.zencdn.net/7.8.4/video.js"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/partials/_footer.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static "css/footer.css" %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/fontawesome.min.css" integrity="sha512-kJ30H6g4NGhWopgdseRb8wTsyllFUYIx3hiUwmGAkgA9B/JbzUBDQVr2VVlWGde6sdBVOG7oU8AL35ORDuMm8g==" crossorigin="anonymous" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/fontawesome.min.js" integrity="sha512-kI12xOdWTh/nL2vIx5Yf3z/kJSmY+nvdTXP2ARhepM/YGcmo/lmRGRttI3Da8FXLDw0Y9hRAyZ5JFO3NrCvvXA==" crossorigin="anonymous"></script>
    <title>Action</title>
  </head>

  <style>

      footer{
          position: relative;
          margin-top: 0px;
          height: auto;
     
      }

      .social__link{
          padding: 12px 12px;
          font-size: 20px !important;
          color: #fff;
      }
      
        
    .deep-purple{
        background-color: lawngreen;
    }
    
    .manu{
        font-size: 16px !important;
    }
    .manu p{
        font-size: 12px !important;
    }
    .footer-copyright{
        font-size: 16px !important;
    }

  </style>
  <body>

    <footer class="page-footer font-small unique-color-dark">

        
        <div style="background-color:rgb(99, 81, 206);">
        <div class="container-fluid social__link">
    
            <!-- Grid row-->
            <div class="row py-4 d-flex align-items-center">
    
            <!-- Grid column -->
            <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
                <h3 class="mb-0">Get connected with us on social networks!</h3>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-6 col-lg-7 text-center text-md-right">
    
                <!-- Facebook -->
                <a class="fb-ic">
                <i class="fa fa-facebook white-text mr-4"> </i>
                </a>
                <!-- Twitter -->
                <a class="tw-ic">
                <i class="fa fa-twitter white-text mr-4"> </i>
                </a>
                <!-- Google +-->
                <a class="gplus-ic">
                <i class="fa fa-google-plus-g white-text mr-4"> </i>
                </a>
                <!--Linkedin -->
                <a class="li-ic">
                <i class="fa fa-linkedin-in white-text mr-4"> </i>
                </a>
                <!--Instagram-->
                <a class="ins-ic">
                <i class="fa fa-whatsapp white-text"> </i>
                </a>
    
            </div>
            <!-- Grid column -->
    
            </div>
            <!-- Grid row-->
    
        </div>
        </div>
    
        <!-- Footer Links -->
        <div style="background-color: rgb(28, 35, 49);" class="container-fluid text-center text-md-left pt-5 text-white">
    
        <!-- Grid row -->
        <div class="row mt-3 manu">
    
            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
    
            <!-- Content -->
            <!-- <h1 class="font-weight-bold">Adivagraphics</h1> -->
        
            <img src="{% static "images/logo.png" %}" alt="Adiva Graphics" class="img-fluid">
    
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
    
            <!-- Links -->
            <h3 class="font-weight-bold">FAQs</h3>
            <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
            <p>
                <a href="#!">Company Related</a>
            </p>
            <p>
                <a href="#!">Service Related</a>
            </p>
        
    
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h3 class="font-weight-bold">Legal</h3>
            <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
            <p>
                <a href="#!">Privacy Policy</a>
            </p>
            <p>
                <a href="#!">Terms of Use</a>
            </p>
    
    
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
    
            <!-- Links -->
            <h3 class="font-weight-bold">Get In Touch</h3>
            <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
            <p>
                <i class="fa fa-home mr-3"></i>455 Hope St, Stamford, CT 06906, USA</p>
            <p>
                <i class="fa fa-envelope mr-3"></i> info@adivagraphics.com</p>
            <!-- <p>
                <i class="fa fa-phone mr-3"></i> + 01 234 567 88</p>
            <p>
                <i class="fa fa-print mr-3"></i> + 01 234 567 89</p> -->
    
            </div>
            <!-- Grid column -->
    
        </div>
        <!-- Grid row -->
    
        </div>
        <!-- Footer Links -->
    
        <!-- Copyright -->
        <div style="background-color: rgb(22, 28, 39);" class="footer-copyright text-center py-3 text-white">© 2020 Copyright:
        <a href="https://adivagraphics.com/"> adivagraphics.com</a>
        </div>
        <!-- Copyright -->
    
    </footer>
  <!-- Footer -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
  </body>
</html>

templates/partials/_icon.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <style>
    .company{
        position: absolute;
        background-color: #000000;
        height: 150px;
        width: 250px;
        left: 10%;
        z-index: 1000;
    }
    .company-icon{
        padding: 5px;
        background-color: #000000;
        height: 150px;
        width: 250px;
    }
  </style>
  <body>
    <div class="company">
        <img src="{% static 'images/logo.png' %}" alt="Adiva Graphics" class="company-icon">
    </div>
  </body>
</html>

templates/partials/_navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/icon-font.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="shortcut icon" type="image/png" href="img/favicon.png">
        
        <title>Natours | Exciting tours for adventurous people</title>
    </head>
    
    <body>
        <div class="navigation">
            <input type="checkbox" class="navigation__checkbox" id="navi-toggle">

            <label for="navi-toggle" class="navigation__button">
                <span class="navigation__icon">&nbsp;</span>
            </label>

            <div class="navigation__background">&nbsp;</div>

            <nav class="navigation__nav">
                <ul class="navigation__list">
                    <li class="navigation__item"><a href="{% url 'home:home' %}" class="navigation__link"><span>01</span>Home</a></li>
                    <li class="navigation__item"><a href="#" class="navigation__link"><span>02</span>Client Login</a></li>
                    <li class="navigation__item"><a href="{% url 'about:about' %}" class="navigation__link"><span>03</span>About Us</a></li>
                    <li class="navigation__item"><a href="{% url 'service:service' %}" class="navigation__link"><span>04</span>Services</a></li>
                    {% comment %} <li class="navigation__item"><a href="#" class="navigation__link"><span>05</span>MindSet</a></li> {% endcomment %}
                    <li class="navigation__item"><a href="{% url 'csr:csr' %}" class="navigation__link"><span>05</span>CSR Activity</a></li>
                    <li class="navigation__item"><a href="{% url 'careers:career' %}" class="navigation__link"><span>06</span>Careers</a></li>
                    <li class="navigation__item"><a href="{% url 'faqs:faqs' %}" class="navigation__link"><span>07</span>FAQs</a></li>
                    <li class="navigation__item"><a href="{% url 'legal:legal' %}" class="navigation__link"><span>08</span>Legal</a></li>
                    </ul>
            </nav>
        </div>
    </body>
</html>

templates/partials/_social.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <style>

   .top-social{
    height: 50vh;
    position: relative;
    background-color: #6CB01A;
    z-index: -1;
    }


    #social{
        height: 100vh !important;
        top: 50%;
        height: auto;
        position: relative;
        background-color: rgb(216, 243, 232);

    }

    .roe{
        padding-bottom: 20px !important;
        margin-bottom: 20px !important;
    }

    .image-group{
        position: absolute;
        left:20%;
        top:2%;
        transform: translate(-10%, -25%);
        background-color: rgb(255, 255, 255, 0.01);
        padding-bottom: 20px;
        /* z-index: 1; */
    }
    .social-image{
        margin: 0px 25px 0px 25px; 
    }

    .social-image-1{
        margin: 0px 25px 0px 25px; 
    }
    .image-style {
        height: 300px;
        width: 300px;
    }

    .row-2{
        padding: 10px;
    }
    .row-1{
        padding: 10px;
    } 

    img{
        padding-bottom:  25px;
        height: 300px;
    }



  </style>
  <body>
    <!-- <section class="top-social">
        <div class="top">
        </div>
    </section>
   <section class="social">
        <div class="top-social">
            <div class="top">
            </div>
        </div>
                <div class="container image-group">
                    <div class="row row-1">
                        <div class="col-md-3 social-image-1">
                            <img class="image-style" src="{% static 'images/social-media/1.jpg' %}" alt="">
                        </div>
                        <div class="col-md-3 social-image-1">
                            <img class="image-style" src="{% static 'images/social-media/4.jpg' %}" alt="">
                        </div>
                        <div class="col-md-3 social-image-1">
                            <img class="image-style" src="{% static 'images/social-media/5.jpg' %}" alt="">
                        </div>
                    </div>
                    <div class="row row-2">
                        <div class="col-md-3 social-image">
                            <img class="image-style" src="{% static 'images/social-media/6.jpg' %}" alt="">
                        </div>
                        <div class="col-md-3 social-image">
                            <img class="image-style" src="{% static 'images/social-media/7.jpg' %}" alt="">
                        </div>
                        <div class="col-md-3 social-image">
                            <img class="image-style" src="{% static 'images/social-media/8.jpg' %}" alt="">
                        </div>
                    </div>
                </div>
    </section> -->



    <section id="social">
        <div class="container">
       
            <div class="row pt-5 pb-5 ">
    
              <div class="col-md-4">
                <div class="thumbnail">
                    <img src="{% static 'images/social-media/6.jpg' %}" alt="Lights" style="width:100%; padding-top: 20px;">
                </div>
              </div>
              <div class="col-md-4">
                <div class="thumbnail">
                    <img src="{% static 'images/social-media/1.jpg' %}" alt="Nature" style="width:100%; padding-top: 20px;">
                </div>
              </div>
              <div class="col-md-4">
                <div class="thumbnail">
                    <img src="{% static 'images/social-media/4.jpg' %}" alt="Fjords" style="width:100%; padding-top: 20px;">
                </div>
              </div>
    
              <div class="col-md-4">
                <div class="thumbnail">
                    <img src="{% static 'images/social-media/5.jpg' %}" alt="Lights" style="width:100%; padding-bottom: 50px;">
                </div>
              </div>
              <div class="col-md-4">
                <div class="thumbnail">
                    <img src="{% static 'images/social-media/7.jpg' %}" alt="Nature" style="width:100%; padding-bottom: 50px;">
                </div>
              </div>
              <div class="col-md-4">
                <div class="thumbnail">
                    <img src="{% static 'images/social-media/8.jpg' %}" alt="Fjords" style="width:100%; padding-bottom: 50px;">
                </div>
              </div>
            </div>
          </div>
    
    </section>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>